controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

summarize:
    path: /summarize
    controller: App\Controller\OnizukaController::summarize
    methods: [POST]